name: FluentAssociation - Release

on:
  push:
    branches: [ master ]

jobs:
  publish-nuget:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - name: Instalando as dependências
      run: |
        cd FluentAssociation/
        dotnet restore
        
    - name: Executando os Testes
      run: |
        cd FluentAssociation/
        dotnet test --nologo --verbosity normal
    
    - name: Buildando os pacotes
      run: |
        cd FluentAssociation/
        dotnet build --configuration Release --no-restore
    
    - name: Publicando no Nuget
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
        PROJECT_FILE_PATH: FluentAssociation/FluentAssociation.Library/FluentAssociation.Library.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
